# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 17:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('validation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Secret',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secrets', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('likes', models.ManyToManyField(to='validation.User')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_secrets', to='validation.User')),
            ],
        ),
    ]
